# coding: utf-8

"""
    API MIOS DIRECT

    API for integration with MIOS DIRECT

    The version of the OpenAPI document: 1.0.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.site_seo_api import SiteSeoApi


class TestSiteSeoApi(unittest.TestCase):
    """SiteSeoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SiteSeoApi()

    def tearDown(self) -> None:
        pass

    def test_create_site_seo(self) -> None:
        """Test case for create_site_seo

        Create site seo
        """
        pass

    def test_return_all_site_seo_to_process(self) -> None:
        """Test case for return_all_site_seo_to_process

        Return all site seo to process
        """
        pass

    def test_return_site_seo_by_base64_url(self) -> None:
        """Test case for return_site_seo_by_base64_url

        Return site seo by base 64 url
        """
        pass

    def test_update_site_seo_score(self) -> None:
        """Test case for update_site_seo_score

        Update site seo score
        """
        pass


if __name__ == '__main__':
    unittest.main()
