# coding: utf-8

"""
    API MIOS DIRECT

    API for integration with MIOS DIRECT

    The version of the OpenAPI document: 1.0.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.template_api import TemplateApi


class TestTemplateApi(unittest.TestCase):
    """TemplateApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TemplateApi()

    def tearDown(self) -> None:
        pass

    def test_create_template(self) -> None:
        """Test case for create_template

        Create template
        """
        pass

    def test_return_all_templates(self) -> None:
        """Test case for return_all_templates

        Return all template
        """
        pass

    def test_return_all_templates_by_project(self) -> None:
        """Test case for return_all_templates_by_project

        Return all template by project
        """
        pass

    def test_return_template_by_name(self) -> None:
        """Test case for return_template_by_name

        Return template by name
        """
        pass


if __name__ == '__main__':
    unittest.main()
