# coding: utf-8

"""
    API MIOS DIRECT

    API for integration with MIOS DIRECT

    The version of the OpenAPI document: 1.0.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.account_api import AccountApi


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountApi()

    def tearDown(self) -> None:
        pass

    def test_add_user_in_product(self) -> None:
        """Test case for add_user_in_product

        Add user in product
        """
        pass

    def test_create_account(self) -> None:
        """Test case for create_account

        Create account
        """
        pass

    def test_delete_user_in_product(self) -> None:
        """Test case for delete_user_in_product

        Delete user in product
        """
        pass

    def test_get_account_by_email_and_password(self) -> None:
        """Test case for get_account_by_email_and_password

        Get account by email and password
        """
        pass

    def test_get_account_by_token(self) -> None:
        """Test case for get_account_by_token

        Get account by token
        """
        pass

    def test_get_user_from_product(self) -> None:
        """Test case for get_user_from_product

        Get user from product
        """
        pass

    def test_link_payment(self) -> None:
        """Test case for link_payment

        Link payment
        """
        pass


if __name__ == '__main__':
    unittest.main()
