# coding: utf-8

"""
    API MIOS DIRECT

    API for integration with MIOS DIRECT

    The version of the OpenAPI document: 1.0.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.hotmart_api import HotmartApi


class TestHotmartApi(unittest.TestCase):
    """HotmartApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HotmartApi()

    def tearDown(self) -> None:
        pass

    def test_service_hotmart_post(self) -> None:
        """Test case for service_hotmart_post

        Service
        """
        pass

    def test_service_hotmart_whats_get(self) -> None:
        """Test case for service_hotmart_whats_get

        Service
        """
        pass

    def test_service_hotmart_whats_post(self) -> None:
        """Test case for service_hotmart_whats_post

        Service
        """
        pass


if __name__ == '__main__':
    unittest.main()
