# coding: utf-8

"""
    API MIOS DIRECT

    API for integration with MIOS DIRECT

    The version of the OpenAPI document: 1.0.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.stripe_api import StripeApi


class TestStripeApi(unittest.TestCase):
    """StripeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StripeApi()

    def tearDown(self) -> None:
        pass

    def test_service_stripe_post(self) -> None:
        """Test case for service_stripe_post

        Service
        """
        pass


if __name__ == '__main__':
    unittest.main()
