# coding: utf-8

"""
    API MIOS DIRECT

    API for integration with MIOS DIRECT

    The version of the OpenAPI document: 1.0.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.product_post import ProductPost

class TestProductPost(unittest.TestCase):
    """ProductPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductPost:
        """Test ProductPost
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductPost`
        """
        model = ProductPost()
        if include_optional:
            return ProductPost(
                id_account_creator = '',
                email_account_creator = '',
                name = '',
                description = '',
                image = '',
                services = [
                    ''
                    ],
                site = '',
                id_account = ''
            )
        else:
            return ProductPost(
                id_account_creator = '',
                email_account_creator = '',
                name = '',
                description = '',
                image = '',
                services = [
                    ''
                    ],
                site = '',
                id_account = '',
        )
        """

    def testProductPost(self):
        """Test ProductPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
