# coding: utf-8

"""
    API MIOS DIRECT

    API for integration with MIOS DIRECT

    The version of the OpenAPI document: 1.0.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.template_post import TemplatePost

class TestTemplatePost(unittest.TestCase):
    """TemplatePost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TemplatePost:
        """Test TemplatePost
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TemplatePost`
        """
        model = TemplatePost()
        if include_optional:
            return TemplatePost(
                id_project = '',
                name = '',
                category = '',
                allow_category_change = True,
                language = '',
                components = [
                    openapi_client.models.template_component.TemplateComponent(
                        type = '', 
                        format = '', 
                        title_if_button = '', 
                        example = '', 
                        link_redirect_if_button = '', )
                    ]
            )
        else:
            return TemplatePost(
                id_project = '',
                name = '',
                category = '',
                allow_category_change = True,
                language = '',
                components = [
                    openapi_client.models.template_component.TemplateComponent(
                        type = '', 
                        format = '', 
                        title_if_button = '', 
                        example = '', 
                        link_redirect_if_button = '', )
                    ],
        )
        """

    def testTemplatePost(self):
        """Test TemplatePost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
