# coding: utf-8

"""
    API MIOS DIRECT

    API for integration with MIOS DIRECT

    The version of the OpenAPI document: 1.0.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.validation_api import ValidationApi


class TestValidationApi(unittest.TestCase):
    """ValidationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ValidationApi()

    def tearDown(self) -> None:
        pass

    def test_create_validation(self) -> None:
        """Test case for create_validation

        Create validation
        """
        pass

    def test_get_validation(self) -> None:
        """Test case for get_validation

        Get validation
        """
        pass


if __name__ == '__main__':
    unittest.main()
