# coding: utf-8

"""
    API MIOS DIRECT

    API for integration with MIOS DIRECT

    The version of the OpenAPI document: 1.0.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.whatsapp_message_clicked_api import WhatsappMessageClickedApi


class TestWhatsappMessageClickedApi(unittest.TestCase):
    """WhatsappMessageClickedApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WhatsappMessageClickedApi()

    def tearDown(self) -> None:
        pass

    def test_create_whatsapp_message_clicked(self) -> None:
        """Test case for create_whatsapp_message_clicked

        Create whatsapp_message_clicked
        """
        pass


if __name__ == '__main__':
    unittest.main()
