# coding: utf-8

"""
    API MIOS DIRECT

    API for integration with MIOS DIRECT

    The version of the OpenAPI document: 1.0.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.invoice_api import InvoiceApi


class TestInvoiceApi(unittest.TestCase):
    """InvoiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InvoiceApi()

    def tearDown(self) -> None:
        pass

    def test_return_invoice_by_email(self) -> None:
        """Test case for return_invoice_by_email

        Return invoice by email
        """
        pass


if __name__ == '__main__':
    unittest.main()
