# coding: utf-8

"""
    API MIOS DIRECT

    API for integration with MIOS DIRECT

    The version of the OpenAPI document: 1.0.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.product_api import ProductApi


class TestProductApi(unittest.TestCase):
    """ProductApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProductApi()

    def tearDown(self) -> None:
        pass

    def test_add_bagy_token_product(self) -> None:
        """Test case for add_bagy_token_product

        Add bagy token to product
        """
        pass

    def test_add_business_id_account_product(self) -> None:
        """Test case for add_business_id_account_product

        Add business id account to product
        """
        pass

    def test_add_phone_number_to_product(self) -> None:
        """Test case for add_phone_number_to_product

        Add phone number to product
        """
        pass

    def test_add_token_meta_product(self) -> None:
        """Test case for add_token_meta_product

        Add token meta to product
        """
        pass

    def test_create_product(self) -> None:
        """Test case for create_product

        Create product
        """
        pass

    def test_return_all_products(self) -> None:
        """Test case for return_all_products

        Return all products
        """
        pass

    def test_return_analytics(self) -> None:
        """Test case for return_analytics

        Return analytics
        """
        pass


if __name__ == '__main__':
    unittest.main()
