# coding: utf-8

"""
    API MIOS DIRECT

    API for integration with MIOS DIRECT

    The version of the OpenAPI document: 1.0.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.add_bagy_token_product_put import AddBagyTokenProductPut

class TestAddBagyTokenProductPut(unittest.TestCase):
    """AddBagyTokenProductPut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddBagyTokenProductPut:
        """Test AddBagyTokenProductPut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddBagyTokenProductPut`
        """
        model = AddBagyTokenProductPut()
        if include_optional:
            return AddBagyTokenProductPut(
                id_product = '',
                bagy_token = ''
            )
        else:
            return AddBagyTokenProductPut(
                id_product = '',
                bagy_token = '',
        )
        """

    def testAddBagyTokenProductPut(self):
        """Test AddBagyTokenProductPut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
