# coding: utf-8

"""
    API MIOS DIRECT

    API for integration with MIOS DIRECT

    The version of the OpenAPI document: 1.0.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.site_seo_put import SiteSeoPut

class TestSiteSeoPut(unittest.TestCase):
    """SiteSeoPut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SiteSeoPut:
        """Test SiteSeoPut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SiteSeoPut`
        """
        model = SiteSeoPut()
        if include_optional:
            return SiteSeoPut(
                id = '',
                performance = 1.337,
                accessibility = 1.337,
                best_practices = 1.337,
                seo = 1.337,
                html_analytics = ''
            )
        else:
            return SiteSeoPut(
                id = '',
                performance = 1.337,
                accessibility = 1.337,
                best_practices = 1.337,
                seo = 1.337,
                html_analytics = '',
        )
        """

    def testSiteSeoPut(self):
        """Test SiteSeoPut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
