# coding: utf-8

"""
    API MIOS DIRECT

    API for integration with MIOS DIRECT

    The version of the OpenAPI document: 1.0.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.whatsapp_message_post import WhatsappMessagePost

class TestWhatsappMessagePost(unittest.TestCase):
    """WhatsappMessagePost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WhatsappMessagePost:
        """Test WhatsappMessagePost
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WhatsappMessagePost`
        """
        model = WhatsappMessagePost()
        if include_optional:
            return WhatsappMessagePost(
                id_message = '',
                wa_id = '',
                wam_id = '',
                wa_profile_name = '',
                phone_number_id = '',
                message_product = '',
                display_phone_number = '',
                profile_name = '',
                from_phone_number = '',
                date_message = '',
                type_message = '',
                body_message = '',
                video_message = '',
                image_message = '',
                document_message = '',
                audio_message = '',
                caption_message = '',
                status_message = ''
            )
        else:
            return WhatsappMessagePost(
                id_message = '',
                wa_id = '',
                wam_id = '',
                wa_profile_name = '',
                phone_number_id = '',
                message_product = '',
                display_phone_number = '',
                profile_name = '',
                from_phone_number = '',
                date_message = '',
                type_message = '',
                body_message = '',
                video_message = '',
                image_message = '',
                document_message = '',
                audio_message = '',
                caption_message = '',
                status_message = '',
        )
        """

    def testWhatsappMessagePost(self):
        """Test WhatsappMessagePost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
