# coding: utf-8

"""
    API MIOS DIRECT

    API for integration with MIOS DIRECT

    The version of the OpenAPI document: 1.0.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.account_post import AccountPost

class TestAccountPost(unittest.TestCase):
    """AccountPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountPost:
        """Test AccountPost
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountPost`
        """
        model = AccountPost()
        if include_optional:
            return AccountPost(
                first_name = '',
                last_name = '',
                image_profile = '',
                email = '',
                country = '',
                password = '',
                phone_number = '',
                provider = ''
            )
        else:
            return AccountPost(
                first_name = '',
                last_name = '',
                email = '',
                country = '',
                password = '',
                phone_number = '',
                provider = '',
        )
        """

    def testAccountPost(self):
        """Test AccountPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
