# coding: utf-8

"""
    API MIAI

    API for integration with MIAI To get started, you need a token where you can get it by do a post request to 'Get account by email and password' and use the token in the header (Authorization: Bearer token) to access the other endpoints 

    The version of the OpenAPI document: 1.0.31
    Contact: oscarsilva@mios.pt
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class WhatsappMessageTemplatePost(BaseModel):
    """
    WhatsappMessageTemplatePost
    """ # noqa: E501
    id_message: StrictStr = Field(description="Id of message")
    wa_id: StrictStr = Field(description="Id of whatsapp")
    wam_id: StrictStr = Field(description="Id of whatsapp message")
    wa_profile_name: StrictStr = Field(description="Profile name of whatsapp")
    phone_number_id: StrictStr = Field(description="Id of phone number")
    message_product: StrictStr = Field(description="Message of product")
    display_phone_number: StrictStr = Field(description="Display phone number")
    profile_name: StrictStr = Field(description="Profile name")
    from_phone_number: StrictStr = Field(description="From phone number")
    date_message: StrictStr = Field(description="Date of message")
    type_message: StrictStr = Field(description="Type of message")
    body_message: StrictStr = Field(description="Body of message")
    video_message: StrictStr = Field(description="Video of message")
    image_message: StrictStr = Field(description="Image of message")
    document_message: StrictStr = Field(description="Document of message")
    audio_message: StrictStr = Field(description="Audio of message")
    caption_message: StrictStr = Field(description="Caption of message")
    status_message: StrictStr = Field(description="Status of message")
    template_name: StrictStr = Field(description="Template name")
    template_type: StrictStr = Field(description="Template type")
    marketing_campaign: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id_message", "wa_id", "wam_id", "wa_profile_name", "phone_number_id", "message_product", "display_phone_number", "profile_name", "from_phone_number", "date_message", "type_message", "body_message", "video_message", "image_message", "document_message", "audio_message", "caption_message", "status_message", "template_name", "template_type", "marketing_campaign"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WhatsappMessageTemplatePost from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if marketing_campaign (nullable) is None
        # and model_fields_set contains the field
        if self.marketing_campaign is None and "marketing_campaign" in self.model_fields_set:
            _dict['marketing_campaign'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WhatsappMessageTemplatePost from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id_message": obj.get("id_message"),
            "wa_id": obj.get("wa_id"),
            "wam_id": obj.get("wam_id"),
            "wa_profile_name": obj.get("wa_profile_name"),
            "phone_number_id": obj.get("phone_number_id"),
            "message_product": obj.get("message_product"),
            "display_phone_number": obj.get("display_phone_number"),
            "profile_name": obj.get("profile_name"),
            "from_phone_number": obj.get("from_phone_number"),
            "date_message": obj.get("date_message"),
            "type_message": obj.get("type_message"),
            "body_message": obj.get("body_message"),
            "video_message": obj.get("video_message"),
            "image_message": obj.get("image_message"),
            "document_message": obj.get("document_message"),
            "audio_message": obj.get("audio_message"),
            "caption_message": obj.get("caption_message"),
            "status_message": obj.get("status_message"),
            "template_name": obj.get("template_name"),
            "template_type": obj.get("template_type"),
            "marketing_campaign": obj.get("marketing_campaign")
        })
        return _obj


